CREATE TABLE books (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    title VARCHAR(100) DEFAULT NULL, 
    author VARCHAR(100) DEFAULT NULL, 
    isbn INTEGER NOT NULL, 
    published_date DATETIME DEFAULT NULL
);
