CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    addresses_id INTEGER NOT NULL, 
    username VARCHAR(25) DEFAULT NULL, 
    enabled BOOLEAN DEFAULT NULL, 
    CONSTRAINT FK_1483A5E95713BC80 
        FOREIGN KEY (addresses_id) 
        REFERENCES addresses (id) 
            NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE UNIQUE INDEX UNIQ_1483A5E95713BC80 
    ON users (addresses_id);
