DROP TABLE addresses;
CREATE TABLE addresses (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    user_id INTEGER NOT NULL, 
    street VARCHAR(30) DEFAULT NULL, 
    city VARCHAR(30) DEFAULT NULL, 
    state VARCHAR(30) DEFAULT NULL
);