CREATE TABLE reviews (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    users_id INTEGER NOT NULL, 
    books_id INTEGER NOT NULL, 
    publicado DATETIME DEFAULT NULL, 
    review_content VARCHAR(255) DEFAULT NULL, 
    CONSTRAINT FK_6970EB0F67B3B43D 
        FOREIGN KEY (users_id) 
        REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION 
            NOT DEFERRABLE INITIALLY IMMEDIATE, 
    CONSTRAINT FK_6970EB0F7DD8AC20 
        FOREIGN KEY (books_id) 
        REFERENCES books (id) ON UPDATE NO ACTION ON DELETE NO ACTION 
            NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IDX_6970EB0F67B3B43D 
    ON reviews (users_id);
CREATE INDEX IDX_6970EB0F7DD8AC20 
    ON reviews (books_id);
