CREATE TABLE addresses (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    user_id INTEGER NOT NULL, 
    street VARCHAR(30) DEFAULT NULL, 
    cirty VARCHAR(30) DEFAULT NULL, 
    satate VARCHAR(30) DEFAULT NULL
);